name: Deploy go app
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Run the thing
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd ${{ secrets.DIRECTORY }}
          git checkout master
          git pull origin master
          /usr/local/go/bin/go build -o bin/app ./cmd/app
          pm2 restart podcast-stats